package FavoriteSitesApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class MainFrame extends javax.swing.JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String username;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(String username) {
        initComponents();
        //fillTable();
        this.username=username;
        try {
            // The newInstance() call is a work around for some
            // broken Java implementations
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";

            conn = DriverManager.getConnection(url, "root", "12345678");

            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        } catch (Exception ex) {
            // handle the error
        }
        filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShareVisitButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DisplayImageButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SharedVisitsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "visitID", "username", "Country Name", "City Name", "Year", "Season Visited", "Best Feature", "Comments", "Rating"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1088, 200));

        ShareVisitButton.setBackground(new java.awt.Color(204, 204, 204));
        ShareVisitButton.setText("Share Visits with your friend");
        ShareVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShareVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShareVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 30));

        RefreshButton.setBackground(new java.awt.Color(204, 204, 204));
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        MenuButton.setBackground(new java.awt.Color(204, 204, 204));
        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisplayImageButton.setBackground(new java.awt.Color(204, 204, 204));
        DisplayImageButton.setText("Display Image");
        DisplayImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayImageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DisplayImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 400, 280));

        SharedVisitsButton.setBackground(new java.awt.Color(204, 204, 204));
        SharedVisitsButton.setText("Shared Visits with me");
        SharedVisitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SharedVisitsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SharedVisitsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 146, 31));

        jLabel2.setText("VisitID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        filltable();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void SharedVisitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SharedVisitsButtonActionPerformed

        try {
        String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
        conn = DriverManager.getConnection(url, "root", "12345678");
        stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        rs = stmt.executeQuery("SELECT v.* FROM visits v JOIN sharedvisits s ON v.visit_id = s.visit_id WHERE s.friend_username = '" + username + "'");
         Table model = new Table(rs, stmt);
        jTable1.setModel(model);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error!");
    }
    }//GEN-LAST:event_SharedVisitsButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        new MenuFrame(username,jTable1).setVisible(true);
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void ShareVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShareVisitButtonActionPerformed
     new ShareVisit(username).setVisible(true);
    }//GEN-LAST:event_ShareVisitButtonActionPerformed

    private void DisplayImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayImageButtonActionPerformed
        
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+jTextField3.getText()+".jpg")));
       
    }//GEN-LAST:event_DisplayImageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("").setVisible(true);
            }
        });
    }
 private void filltable(){
    try {
        String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
        conn = DriverManager.getConnection(url, "root", "12345678");
        stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        rs = stmt.executeQuery("SELECT * FROM visits");
         Table model = new Table(rs, stmt);
        jTable1.setModel(model);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error!");
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayImageButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton ShareVisitButton;
    private javax.swing.JButton SharedVisitsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
