/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FavoriteSitesApp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author pc
 */
public class MenuFrame extends javax.swing.JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String username;
    JTable table;
    /**
     * Creates new form MenuFrame
     */
    public MenuFrame(String username,JTable table) {
        this.username=username;
        initComponents();
        this.table=table;
        setDefaultCloseOperation(MenuFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddVisitButton = new javax.swing.JButton();
        UpdateVisitButton = new javax.swing.JButton();
        DeleteVisitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BestCountriesForFood = new javax.swing.JButton();
        MostVisitedButton = new javax.swing.JButton();
        SpringButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        SearchByYearButton = new javax.swing.JButton();
        DisplayVisitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddVisitButton.setText("Add Visit");
        AddVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 89, 50));

        UpdateVisitButton.setText("Update Visit");
        UpdateVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 20));

        DeleteVisitButton.setText("Delete Visit");
        DeleteVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 20));

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 41, -1));

        BestCountriesForFood.setText("Best Countries for Food");
        BestCountriesForFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestCountriesForFoodActionPerformed(evt);
            }
        });
        getContentPane().add(BestCountriesForFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 163, 40));

        MostVisitedButton.setText("Most Visited Countries");
        MostVisitedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostVisitedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MostVisitedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 163, 40));

        SpringButton.setText("Visits only for spring");
        SpringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpringButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SpringButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 163, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, -1));

        SearchByYearButton.setText("Search by year");
        SearchByYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByYearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchByYearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        DisplayVisitButton.setText("Display Visit");
        DisplayVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVisitButtonActionPerformed
   new AddVisit(username).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddVisitButtonActionPerformed

    private void DeleteVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVisitButtonActionPerformed
        String visitID = jTextField1.getText();
if (visitID.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter an ID to delete.");
    return;
}
try {
    String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
    conn = DriverManager.getConnection(url, "root", "12345678");

    int id = Integer.parseInt(visitID);  
    String sql = "DELETE FROM sharedvisits WHERE visit_id = ?";
    try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setInt(1, id);
        pstmt.executeUpdate();
    }
    sql = "DELETE FROM visits WHERE visit_id = ?";
    try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
        int rowsAffected;
        pstmt.setInt(1, id);
        rowsAffected = pstmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Visit deleted.");
            
        } else {
            JOptionPane.showMessageDialog(this, "Visit not found.");
        }
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid ID format. Please enter a number.");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_DeleteVisitButtonActionPerformed

    private void BestCountriesForFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestCountriesForFoodActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
            conn = DriverManager.getConnection(url, "root", "12345678");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            rs = stmt.executeQuery("SELECT country_name, COUNT(*) as visits FROM visits WHERE best_feature = 'Food' GROUP BY country_name ORDER BY visits DESC");
            Table model = new Table(rs, stmt);
            table.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }//GEN-LAST:event_BestCountriesForFoodActionPerformed

    private void MostVisitedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostVisitedButtonActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
            conn = DriverManager.getConnection(url, "root", "12345678");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            rs = stmt.executeQuery("SELECT country_name, COUNT(*) AS visits FROM visits where username = '"+username+"' GROUP BY country_name ORDER BY visits DESC;");
            Table model = new Table(rs, stmt);
            table.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }//GEN-LAST:event_MostVisitedButtonActionPerformed

    private void SpringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpringButtonActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
            conn = DriverManager.getConnection(url, "root", "12345678");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            rs = stmt.executeQuery("SELECT DISTINCT country_name FROM visits WHERE season_visited = 'Spring';");
            Table model = new Table(rs, stmt);
            table.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }//GEN-LAST:event_SpringButtonActionPerformed

    private void SearchByYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByYearButtonActionPerformed
        String year= jTextField2.getText();
        try {
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
            conn = DriverManager.getConnection(url, "root", "12345678");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            rs = stmt.executeQuery("Select * from visits where year_visited="+year+";");
            Table model = new Table(rs, stmt);
            table.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }//GEN-LAST:event_SearchByYearButtonActionPerformed

    private void UpdateVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVisitButtonActionPerformed
        new UpdateVisit(username,Integer.parseInt(jTextField1.getText())).setVisible(true);
    }//GEN-LAST:event_UpdateVisitButtonActionPerformed

    private void DisplayVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayVisitButtonActionPerformed
        String visitID = jTextField1.getText();
         try {
            String url = "jdbc:mysql://localhost:3306/favoritesitesdb";
            conn = DriverManager.getConnection(url, "root", "12345678");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            rs = stmt.executeQuery("SELECT * FROM visits WHERE visit_id = "+ visitID+";");
            Table model = new Table(rs, stmt);
            table.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }//GEN-LAST:event_DisplayVisitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVisitButton;
    private javax.swing.JButton BestCountriesForFood;
    private javax.swing.JButton DeleteVisitButton;
    private javax.swing.JButton DisplayVisitButton;
    private javax.swing.JButton MostVisitedButton;
    private javax.swing.JButton SearchByYearButton;
    private javax.swing.JButton SpringButton;
    private javax.swing.JButton UpdateVisitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
